export const coursesData = [
	// Beauty & Salon Courses
	{
		id: 1,
		name_en: "Hair dressing, Makeup & Styling",
		name_sw: "Kusuka Nywele, Makeup & Ususi",
		category: "beauty",
		category_en: "Beauty & Salon Courses",
		category_sw: "Kozi za Urembo na Saluni",
		icon: "💄",
		duration: 6,
		durationText_en: "6 Months",
		durationText_sw: "Miezi 6",
		fee: 600000,
		feeWithHostel: 780000,
		description_en: "Comprehensive hair dressing and makeup styling course",
		description_sw: "Kozi kamili ya kusuka nywele na ususi makeup",
	},
	{
		id: 2,
		name_en: "Hair dressing, Makeup & Styling",
		name_sw: "Kusuka Nywele, Makeup & Ususi",
		category: "beauty",
		category_en: "Beauty & Salon Courses",
		category_sw: "Kozi za Urembo na Saluni",
		icon: "💄",
		duration: 3,
		durationText_en: "3 Months",
		durationText_sw: "Miezi 3",
		fee: 300000,
		feeWithHostel: 390000,
		description_en: "Intermediate hair dressing and makeup styling course",
		description_sw: "Kozi ya kati ya kusuka nywele na ususi makeup",
	},
	{
		id: 3,
		name_en: "Hair Dressing Only",
		name_sw: "Kusuka Nywele Tu",
		category: "beauty",
		category_en: "Beauty & Salon Courses",
		category_sw: "Kozi za Urembo na Saluni",
		icon: "💄",
		duration: 2,
		durationText_en: "2 Months",
		durationText_sw: "Miezi 2",
		fee: 250000,
		feeWithHostel: 310000,
		description_en: "Hair dressing techniques and styling",
		description_sw: "Mbinu za kusuka nywele na ususi",
	},
	{
		id: 4,
		name_en: "Full Makeup & Hair Styling",
		name_sw: "Makeup Kamili & Ususi Nywele",
		category: "beauty",
		category_en: "Beauty & Salon Courses",
		category_sw: "Kozi za Urembo na Saluni",
		icon: "💄",
		duration: 1,
		durationText_en: "1 Month",
		durationText_sw: "Mwezi 1",
		fee: 150000,
		feeWithHostel: 180000,
		description_en: "Intensive full makeup and hair styling course",
		description_sw: "Kozi ya haraka ya makeup na ususi nywele",
	},
	{
		id: 5,
		name_en: "Nail Art",
		name_sw: "Sanaa ya Kucha",
		category: "beauty",
		category_en: "Beauty & Salon Courses",
		category_sw: "Kozi za Urembo na Saluni",
		icon: "💄",
		duration: 2,
		durationText_en: "2 Months",
		durationText_sw: "Miezi 2",
		fee: 300000,
		feeWithHostel: 360000,
		description_en: "Nail art design and decoration techniques",
		description_sw: "Sanaa ya kucha na mbinu za kucha",
	},
	// Other Skill Courses
	{
		id: 6,
		name_en: "Decoration (Event Décor)",
		name_sw: "Uswazi (Uswazi wa Matukio)",
		category: "skills",
		category_en: "Other Skill Courses",
		category_sw: "Kozi Zingine za Ustadi",
		icon: "🎨",
		duration: 2,
		durationText_en: "2 Months",
		durationText_sw: "Miezi 2",
		fee: 400000,
		feeWithHostel: 460000,
		description_en: "Event decoration and styling for various occasions",
		description_sw: "Uswazi wa matukio na mbinu za styling",
	},
	{
		id: 7,
		name_en: "Cake Decoration",
		name_sw: "Uswazi wa Keki",
		category: "skills",
		category_en: "Other Skill Courses",
		category_sw: "Kozi Zingine za Ustadi",
		icon: "🎨",
		duration: 1,
		durationText_en: "1 Month",
		durationText_sw: "Mwezi 1",
		fee: 300000,
		feeWithHostel: 330000,
		description_en: "Cake decoration and baking techniques",
		description_sw: "Uswazi wa keki na mbinu za kupika keki",
	},
	{
		id: 8,
		name_en: "Fashion Design, Sewing & Cloth Technology",
		name_sw: "Muundo wa Mavazi, Kushona & Teknolojia ya Nguo",
		category: "skills",
		category_en: "Other Skill Courses",
		category_sw: "Kozi Zingine za Ustadi",
		icon: "🎨",
		duration: 6,
		durationText_en: "6 Months",
		durationText_sw: "Miezi 6",
		fee: 600000,
		feeWithHostel: 780000,
		description_en: "Complete fashion design, sewing and textile technology",
		description_sw: "Muundo wa mavazi kamili, kushona na teknolojia",
	},
	{
		id: 9,
		name_en: "Henna (Hina/Piko)",
		name_sw: "Henna (Hina/Piko)",
		category: "skills",
		category_en: "Other Skill Courses",
		category_sw: "Kozi Zingine za Ustadi",
		icon: "🎨",
		duration: 1,
		durationText_en: "1 Month",
		durationText_sw: "Mwezi 1",
		fee: 150000,
		feeWithHostel: 180000,
		description_en: "Henna design and application techniques",
		description_sw: "Mbinu za henna na muundo wa henna",
	},
];
